#index:
#    path: /
#    controller: App\Controller\DefaultController::index
menu:
    path: /api/menu
    controller: App\Controller\Menu\IndexController::index
multselect-teacher:
    path: /api/multselect/teacher
    controller: App\Controller\Multselect\TeacherController::index
table-exam:
    path: /api/table/exam
    controller: App\Controller\Table\ExamController::index

doc-index:
    path: /
    controller: App\Controller\BaseController::index
api-menu:
    path: /api-menu
    controller: App\Controller\Menu\BaseController::index
mock-menu-return:
    path: /mock/menu/return
    controller: App\Controller\Menu\BaseController::return
mock-menu-confirm:
    path: /mock/menu/confirm
    controller: App\Controller\Menu\BaseController::confirm
mock-menu-error:
    path: /mock/menu/error
    controller: App\Controller\Menu\BaseController::error

api-multselect:
    path: /api-multselect
    controller: App\Controller\Multselect\BaseController::index
mock-multselect-return:
    path: /mock/multselect/return
    controller: App\Controller\Multselect\BaseController::return
mock-multselect-confirm:
    path: /mock/multselect/confirm
    controller: App\Controller\Multselect\BaseController::confirm
mock-multselect-error:
    path: /mock/multselect/error
    controller: App\Controller\Multselect\BaseController::error

api-table:
    path: /api-table
    controller: App\Controller\Table\BaseController::index
mock-table-return:
    path: /mock/table/return
    controller: App\Controller\Table\BaseController::return
mock-table-confirm:
    path: /mock/table/confirm
    controller: App\Controller\Table\BaseController::confirm
mock-table-error:
    path: /mock/table/error
    controller: App\Controller\Table\BaseController::error