#index:
#    path: /
#    controller: App\Controller\DefaultController::index
menu:
    path: /api/menu
    controller: App\Controller\Menu\IndexController::list

multselect-teacher:
    path: /api/multselect/teacher
    controller: App\Controller\Multselect\TeacherController::search

login:
    path: /api/login
    controller: App\Controller\Table\TeacherController::login

table-exam:
    path: /api/table/exam
    controller: App\Controller\Table\ExamController::search
table-exam-edit:
    path: /api/table/exam/edit
    controller: App\Controller\Table\ExamController::edit
table-exam-delete:
    path: /api/table/exam/delete
    controller: App\Controller\Table\ExamController::delete
table-exam-remind:
    path: /api/table/exam/remind
    controller: App\Controller\Table\ExamController::remind
table-exam-new:
    path: /api/table/exam/new
    controller: App\Controller\Table\ExamController::new

table-teacher:
    path: /api/table/teacher
    controller: App\Controller\Table\TeacherController::search
table-teacher-self:
    path: /api/table/teacher/self
    controller: App\Controller\Table\TeacherController::viewSelf
table-teacher-edit:
    path: /api/table/teacher/edit
    controller: App\Controller\Table\TeacherController::edit
table-teacher-edit-self:
    path: /api/table/teacher/edit/self
    controller: App\Controller\Table\TeacherController::editSelf
table-teacher-delete:
    path: /api/table/teacher/delete
    controller: App\Controller\Table\TeacherController::delete
table-teacher-permit:
    path: /api/table/teacher/permit
    controller: App\Controller\Table\TeacherController::changePermit
table-teacher-new:
    path: /api/table/teacher/new
    controller: App\Controller\Table\TeacherController::new


table-task-new:
    path: /api/table/task/new
    controller: App\Controller\Table\taskController::new
table-task-message:
    path: /api/table/task/message
    controller: App\Controller\Table\taskController::message
table-task-file:
    path: /api/table/task/file
    controller: App\Controller\Table\taskController::fileTask
table-task-message-view:
    path: /api/table/task/message/view
    controller: App\Controller\Table\taskController::messageView
table-task-file-view:
    path: /api/table/task/file/view
    controller: App\Controller\Table\taskController::fileView
table-task-message-answer:
    path: /api/table/task/message/answer
    controller: App\Controller\Table\taskController::messageAnswer
table-task-file-answer:
    path: /api/table/task/file/answer
    controller: App\Controller\Table\taskController::fileAnswer
table-task-file-upload:
    path: /api/table/task/file/upload
    controller: App\Controller\Table\taskController::fileupload
table-task-file-download:
    path: /api/table/task/file/download
    controller: App\Controller\Table\taskController::fileDownload
