#index:
#    path: /
#    controller: App\Controller\DefaultController::index
doc-index:
    path: /
    controller: App\Controller\BaseController::index
doc-menu:
    path: /api-menu
    controller: App\Controller\Menu\BaseController::index
doc-multiselect:
    path: /api-multiselect
    controller: App\Controller\Multiselect\BaseController::index
doc-tablesearch:
    path: /api-tablesearch
    controller: App\Controller\Tablesearch\BaseController::index